# Site settings
title: unfoldingWord
email: info@unfoldingWord.org
description: Unrestricted biblical content in every language
keywords: Unrestricted biblical content in every language
baseurl: "" # the subpath of your site, e.g. /blog, must NOT end with a slash (/)
url: "https://unfoldingword.org" # the base hostname & protocol for your site
twitter_username: unfoldingWord
github_username:  unfoldingWord-dev
python_command: /usr/bin/env python2

# this is the source for building the translation academy page
ta_endpoint: "https://api.unfoldingword.org/ta/txt/1/en/"
ta_pdf_cdn: "http://cdn.door43.org/en/ta/v5/pdf/"

keep_files: [assets, assets/docs, assets/vid, assets/img, css/fonts, slides]

exclude: [Gemfile*, s3_excludes, s3_push.sh, open-uri*, vendor]

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
